### ISSUE TITLE
Latest Docker build fails after sqlite database migration "create_last_times"

### ISSUE THREAD

**Issue by oztourer** [toddsundsted/ktistec#94] opened 2024-03-11 23:40 UTC
On rebuilding my Docker image of ktistec from the latest -dist branch I get an error loop from which it fails to recover:
```
 SQLite3 version 3.40.1
 Unhandled exception: Missing JSON attribute: last_timeline_checked_at
   parsing Temp_20231204140457::State at line 1, column 1
   deserializing Temp_20231204140457#state (DB::MappingException)
   from ???
   from ???
   from ???
   from ???
   from src/env/__libc_start_main.c:95:2 in 'libc_start_main_stage2'
 Caused by: Missing JSON attribute: last_timeline_checked_at
   parsing Temp_20231204140457::State at line 1, column 1 (JSON::SerializableError)
   from ???
   from ???
   from ???
   from ???
   from src/env/__libc_start_main.c:95:2 in 'libc_start_main_stage2'
```
I browsed the sqlite database and found that migration record 'create_last_times' had been created and that table 'last_times' exists but is empty. The error above repeats indefinitely and always for the same date and time stamp. My only solution for now is to revert to a version of ktistec which does not require this table.

Without doing a deep dive into the source of ktistec I cannot see a way to resolve this so suggestions would be welcome.

**Comment by toddsundsted** [comment] 2024-03-12 00:54
this is a duplicate of https://github.com/toddsundsted/ktistec/issues/92

i'd like to move the discussion over there. i will tag you in a comment on that thread.

**Closed** 2024-03-12 02:22 UTC
Labels: duplicate

**Comment by oztourer** [comment] 2024-03-12 04:50
Just to let you know Todd, your fix worked and my instance is back on air. Many thanks for the quick response.
