### ISSUE TITLE
Unable to follow a.gup.pe groups

### ISSUE THREAD

**Issue by vrthra** [toddsundsted/ktistec#31] opened 2022-11-12 20:34 UTC
I am trying to follow an a.gup.pe group, but I get this error when trying to do that. 

![gupe](https://user-images.githubusercontent.com/70410/201493521-cb1f6be6-8c7d-4637-832f-921f23b26c48.jpg)

However, I am able to do this from my mastodon account at scholar.social and fediscience.org.

**Comment by vrthra** [comment] 2022-11-12 20:36
I can also confirm that this works from my machine where ktistec is deployed
```
$ telnet a.gup.pe 80
Trying 143.244.172.205...
Connected to a.gup.pe.
Escape character is '^]'.
GET /

HTTP/1.1 307 Temporary Redirect
Location: https://undefined/
Date: Sat, 12 Nov 2022 20:35:23 GMT
Connection: close

Connection closed by foreign host.
```

**Comment by JayVii** [comment] 2022-11-12 21:17
I cannot confirm this. Which ktistec Version are you running.

![Screenshot_20221112-221417](https://user-images.githubusercontent.com/28513043/201494876-b2fcc115-e871-4508-80e3-91507e350925.png)

![Screenshot_20221112-221435](https://user-images.githubusercontent.com/28513043/201494870-5fc85535-7870-4ec9-9e44-5467ce633ccc.png)


a.gup.pe offen times behaves unstable. This looks like their Server had a (temporary?) issues with redirects, no?

**Comment by vrthra** [comment] 2022-11-12 21:39
Hmm, it could be that my version is old. Is there a file in the deployed instance I can look for the version? I don't have access to my build machine currently (for the coming week), but can access the docker image.

**Comment by JayVii** [comment] 2022-11-12 21:48
The Version is shown on the login page of your instance, right und er the login button

**Comment by vrthra** [comment] 2022-11-12 22:08
Hmm, it is Ktistec Version `2.0.0-2` I will check again with `2.0.0-3` when I get the chance.

**Comment by toddsundsted** [comment] 2022-11-13 10:01
there won't be any different between the two version in regards to this functionality.

looking at the telnet trace, the Location header makes no sense (Location: https://undefined/). maybe the issue is with hitting the non-secure HTTP endpoint.

**Comment by vrthra** [comment] 2022-11-13 14:52
@toddsundsted 
The location header is undefined because it uses a virtual host, and relies on a host to be sent over http. See below.
```
rahul@instance-web:~$ telnet a.gup.pe 80
Trying 143.244.172.205...
Connected to a.gup.pe.
Escape character is '^]'.
GET / HTTP/1.0
Host: a.gup.pe

HTTP/1.1 307 Temporary Redirect
Location: https://a.gup.pe/
Date: Sun, 13 Nov 2022 14:50:52 GMT
Connection: close

Connection closed by foreign host.
```

I am not sure why it is hitting port 80 though.

**Comment by toddsundsted** [comment] 2022-11-26 14:24
at this point i can't reproduce the original issue—i'm assuming the site was having problems.

there *is* still a problem. guppe sends over the handle for the remote account to follow instead of the URL of the account so on ktistec you get a "Can't Dereference URI" (because it's not a uri). it would be easy enough to lookup the account via webfinger, etc. etc. but i just realized that mastodon is moving on from the remote follow flow. following a user from the user's own page now asks you to "Copy and paste this URL into the search field of your favourite Mastodon app or the web interface of your Mastodon server."

so i'm inclined close this and leave it "unfixed". the remote follow flow is hard to implement, and it's hard for people to follow, and if mastodon is moving on i think it's day a numbered, generally.

**Comment by vrthra** [comment] 2022-11-27 00:23
This seems to no longer happen, but I found that it is this site that is responsible for `OrderedCollection` being sent. The logs attached. The logs were generated as a result of these actions:

1) unfollowing the `seresearchers@a.gu.pe`
2) following `seresearchers@a.gu.pe`

[ktistec.log](https://github.com/toddsundsted/ktistec/files/10097266/ktistec.log)

**Comment by toddsundsted** [comment] 2022-11-27 00:58
thanks!

**Comment by toddsundsted** [comment] 2022-11-27 18:58
> so i'm inclined close this and leave it "unfixed".

eh, i changed my mind and fixed this. remote follow for a.gup.pe now works (at least the follow part—i haven't looked into the collection issue.)

**Comment by toddsundsted** [comment] 2022-12-07 12:12
the collection issue should be fixed in https://github.com/toddsundsted/ktistec/commit/fb7c7ba1e6ddff725529d738d823206515fa15cc as well

**Closed** 2022-12-11 19:06 UTC
Labels: bug
