### ISSUE TITLE
Wrong notifications about mentions

### ISSUE THREAD

**Issue by JayVii** [toddsundsted/ktistec#21] opened 2022-11-07 20:30 UTC
I just installed `2.0.0-3` and get random notifications of being mentioned in posts where I am not actually mentioned in. Looks like fbec729bebb83548f11ed8073741d02fdeec113e is overdoing something there.

**Comment by toddsundsted** [comment] 2022-11-08 07:05
@JayVii were those posts replies to your post? i added support for replies since sometimes people reply to post but don't mention me. maybe the labeling needs to be adjusted.

**Comment by JayVii** [comment] 2022-11-08 07:28
No, they are not directed at me. As soon as I built the 2.0.0-3 docker image and deployed it, i got multiple notifications per minute. All from posts where someone i follow reponds to somebody else. I was never involved there

**Comment by toddsundsted** [comment] 2022-11-08 08:24
thanks! ok looking at the logic again. you can delete that rule in the meantime. i will also add some functionality to recreate notifications and the timeline with the fix.

i usually test on my own instance before releasing, but i rushed these fixes out. :-(

**Comment by felixkrohn** [comment] 2022-11-11 08:18
I can confirm this behaviour and am available for further tests as well, if needed.

**Comment by JayVii** [comment] 2022-11-12 08:54
FYI, for the meantime, I am running 2.0.0-3 with the rules set from 2.0.0-2. Working great!

**Comment by toddsundsted** [comment] 2022-11-15 11:20
i haven't been able to reproduce this, either via tests, or by setting up several instances of ktistec. i'm home again after traveling so i'll deply this myself and see if that help.

**Comment by toddsundsted** [comment] 2022-11-16 12:55
this should be fixed now. i have a couple more related changes to make before it's complete but the underlying bug is fixed.

replied to objects are not always cached locally but the match was succeeding with nothing bound. subsequent conditions then matched and bound values incorrectly.

**Comment by toddsundsted** [comment] 2022-11-16 12:55
leaving this open, pending confirmations.

**Comment by JayVii** [comment] 2022-11-16 19:13
Just built the image and deployed it. Works as it should!

**Comment by toddsundsted** [comment] 2022-11-16 23:13
thanks @JayVii

i've been running it all day and it seems to fix the problem.

closing.

**Closed by toddsundsted** 2022-11-16 23:13 UTC
Labels: bug

**Comment by toddsundsted** [comment] 2022-11-16 23:14
one final note. i have a commit already to go with a migration that will clean up the incorrect notifications. it will drop tomorrow.

**Comment by JayVii** [comment] 2022-11-17 05:58
Thank you a lot @toddsundsted!

**Comment by felixkrohn** [comment] 2022-11-17 15:41
Took me a bit to test, but can now also confirm: works as expected 💯
Thanks!

**Comment by toddsundsted** [comment] 2022-11-17 17:23
i added a migration to automatically clean up the incorrect notifications. if you have lot of messages (almost three years, like i do) it uses too much memory, and you might want to wait until i push a fix for that. both otherwise it will run automatically if you build a server from the latest main.

**Comment by felixkrohn** [comment] 2022-11-17 21:24
heads-up for those trying it: make sure you have a backup of your DB before. In my case the container crashed and, after reverting to the former image, all posts, followers and followings were gone so that I had to restore the DB.
Not sure if I did anything wrong?
```
  from src/env/__libc_start_main.c:95:2 in 'libc_start_main_stage2'
Unhandled exception: more than one row (DB::Error)
  from ???
  from ???
```
